### ISSUE TITLE
audio files (.wav) are missing in the repository

### ISSUE THREAD

**Issue by sawood-cloud** [theadamsabra/LearningFromAudio#1]
Hi,
I noticed that audio files are missing in the repository. pls check. eg: snippets/rb.wav .

Thank you.

**Comment by theadamsabra** [comment]
Hi, @sawood-cloud, because of copyright issues, I am not allowed to share the snippets. If you would like me to create a few functions to create your own snippets of your favorite songs, let me know!

**Comment by sawood-cloud** [comment]
Thank you for the quick response, much appreciated.   Kindly provide the functions for creation of snippets.

**Comment by theadamsabra** [comment]
No worries! I'll work on it in a few and try to get it uploaded by the end of the day. I'll let you know when it's up and working.

**Comment by theadamsabra** [comment]
@sawood-cloud, I just added the function and added a quick tutorial in the README. Thanks for raising this issue!
